# Site settings
name: Sanath Kumar
title: Sanath Kumar | Software Engineer
description: Software engineer focused on building products, services to make customers and engineers life better
url: https://sanathk.com/
baseurl: ""
email: sanath@sanathk.com
cover: https://sanathk.com/img/og.png
logo: https://sanathk.com/img/emojis/technologist.png
resume: https://sanathk.com/resume.pdf
social:
  - title: email
    url: mailto:sanath@sanathk.com
  - title: linkedin
    url: https://www.linkedin.com/in/sanathkumarbs
  - title: github
    url: https://github.com/sanathkumarbs
  # - title: instagram
  #   url: https://instagram.com/sanathkumarbs
  # - title: twitter
  #   url: https://twitter.com/sanathkumarbs

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
